/**
 * 
 */
package org.vme.web.service.io;

import java.util.UUID;

/**
 * @author Fabrizio Sibeni
 * 
 */
public class ServiceRequest {

	/**
	 * UUID of the request. Generated by the system on request action
	 */
	private UUID uuid;

	/**
	 * @param uuid
	 */
	public ServiceRequest(UUID uuid) {
		super();
		this.uuid = uuid;
	}

	/**
	 * @return the uuid of the request
	 */
	public String getUuid() {
		return uuid.toString();
	}

}
