/**
 * 
 */
package org.vme.service.dto;

import java.util.UUID;

/**
 * @author Fabrizio Sibeni
 *
 */
public class VmeGetRequestDto implements VmeRequestDto {

	/**
	 * UUID of the request. Generated by the system on request action
	 */
	private UUID uuid;
	
	/**
	 * Identifier of the requested VME object. 
	 */
	private long id;

	
	/**
	 * @param uuid
	 */
	public VmeGetRequestDto(UUID uuid) {
		super();
		this.uuid = uuid;
	}
	
	
	
	

	/**
	 * @return the id
	 */
	public long getId() {
		return id;
	}





	/**
	 * @param id the id to set
	 */
	public void setId(long id) {
		this.id = id;
	}





	/**
	 * @return the uuid
	 */
	public String getUuid() {
		return uuid.toString();
	}
	
	
	
	

	
	
	
	
}
