/**
 * 
 */
package org.vme.service.dto;

import java.util.UUID;

/**
 * @author Fabrizio Sibeni
 *
 */
public class VmeGetRequestDto implements VmeRequestDto {

	/**
	 * UUID of the request. Generated by the system on request action
	 */
	private UUID uuid;
	
	/**
	 * Internal Identifier of the requested VME object. 
	 */
	private long id;
	
	
	/**
	 * Geographical Identifier of the requested VME object. 
	 */
	private String geographicFeatureId;
	
	/**
	 * Inventory identifier of the requested VME object. 
	 */
	private String inventoryIdentifier;

	
	/**
	 * @param uuid
	 */
	public VmeGetRequestDto(UUID uuid) {
		super();
		this.uuid = uuid;
	}
	
	
	
	

	/**
	 * @return the id
	 */
	public long getId() {
		return id;
	}





	/**
	 * @param id the id to set
	 */
	public void setId(long id) {
		this.id = id;
	}

	/**
	 * @return the geographicFeatureId
	 */
	public String getGeographicFeatureId() {
		return geographicFeatureId;
	}

	/**
	 * @param geographicFeatureId the geographicFeatureId to set
	 */
	public void setGeographicFeatureId(String geographicFeatureId) {
		this.geographicFeatureId = geographicFeatureId;
	}

	/**
	 * @return <code>true</code> if request has the geographicFeatureId not null, <code>false</code> otherwise
	 */
	public boolean hasGeographicFeatureId() {
		return geographicFeatureId!=null;
	}




	/**
	 * @return the inventoryIdentifier
	 */
	public String getInventoryIdentifier() {
		return inventoryIdentifier;
	}

	/**
	 * @param inventoryIdentifier the inventoryIdentifier to set
	 */
	public void setInventoryIdentifier(String inventoryIdentifier) {
		this.inventoryIdentifier = inventoryIdentifier;
	}

	/**
	 * @return <code>true</code> if request has the inventoryIdentifier not null, <code>false</code> otherwise
	 */
	public boolean hasInventoryIdentifier() {
		return inventoryIdentifier!=null;
	}
	


	/**
	 * @return the uuid
	 */
	public String getUuid() {
		return uuid.toString();
	}






	
	
	
	

	
	
	
	
}
