/**
 * 
 */
package org.vme.service.dto;

import java.util.UUID;

/**
 * @author Fabrizio Sibeni
 *
 */
public class VmeSearchRequestDto implements VmeRequestDto {

	/**
	 * UUID of the request. Generated by the system on request action
	 */
	private UUID uuid;
	
	/**
	 * Competent authority unique identifier. 
	 */
	private int authority;

	/**
	 * VME status unique identifier. 
	 */
	private int type ;

	/**
	 * VME criteria unique identifier. 
	 */
	private int criteria ;
	
	/**
	 * VME request Year . 
	 */
	private int year;
	
	/**
	 * VME textual field by which the search is performed. 
	 */
	private String text;

	
	
	/**
	 * @param uuid
	 */
	public VmeSearchRequestDto(UUID uuid) {
		super();
		this.uuid = uuid;
	}
	
	
	
	
	
	
	/**
	 * @return the authority
	 */
	public int getAuthority() {
		return authority;
	}

	/**
	 * @param authority the authority to set
	 */
	public void setAuthority(int authority) {
		this.authority = authority;
	}


	/**
	 * @return the type
	 */
	public int getType() {
		return type;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(int type) {
		this.type = type;
	}

	/**
	 * @return the criteria
	 */
	public int getCriteria() {
		return criteria;
	}

	/**
	 * @param criteria the criteria to set
	 */
	public void setCriteria(int criteria) {
		this.criteria = criteria;
	}

	/**
	 * @return the year
	 */
	public int getYear() {
		return year;
	}

	/**
	 * @param year the year to set
	 */
	public void setYear(int year) {
		this.year = year;
	}

	/**
	 * @return the text
	 */
	public String getText() {
		return text;
	}

	/**
	 * @param text the text to set
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * @return the uuid of the request
	 */
	public String getUuid() {
		return uuid.toString();
	}
	
	
	
	

	
	
	
	
}
