/**
 * 
 */
package org.vme.service.dto;

import java.util.UUID;

/**
 * @author Fabrizio Sibeni
 *
 */
public class VmeSearchRequestDto {

	/**
	 * UUID of the request. Generated by the system on request action
	 */
	private UUID uuid;
	
	/**
	 * Competent authority unique identifier. 
	 */
	private int authority;

	/**
	 * Area type unique identifier. 
	 */
	private int areatype ;
	
	/**
	 * VME status unique identifier. 
	 */
	private int status ;

	/**
	 * VME criteria unique identifier. 
	 */
	private int criteria ;
	
	/**
	 * VME request Year . 
	 */
	private int year;
	
	/**
	 * VME textual field by which the search is performed. 
	 */
	private String text;

	
	
	/**
	 * @param uuid
	 */
	public VmeSearchRequestDto(UUID uuid) {
		super();
		this.uuid = uuid;
	}
	
	
	
	
	
	
	/**
	 * @return the authority
	 */
	public int getAuthority() {
		return authority;
	}

	/**
	 * @param authority the authority to set
	 */
	public void setAuthority(int authority) {
		this.authority = authority;
	}

	/**
	 * @return the areatype
	 */
	public int getAreatype() {
		return areatype;
	}

	/**
	 * @param areatype the areatype to set
	 */
	public void setAreatype(int areatype) {
		this.areatype = areatype;
	}

	/**
	 * @return the status
	 */
	public int getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(int status) {
		this.status = status;
	}

	/**
	 * @return the criteria
	 */
	public int getCriteria() {
		return criteria;
	}

	/**
	 * @param criteria the criteria to set
	 */
	public void setCriteria(int criteria) {
		this.criteria = criteria;
	}

	/**
	 * @return the year
	 */
	public int getYear() {
		return year;
	}

	/**
	 * @param year the year to set
	 */
	public void setYear(int year) {
		this.year = year;
	}

	/**
	 * @return the text
	 */
	public String getText() {
		return text;
	}

	/**
	 * @param text the text to set
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * @return the uuid
	 */
	public String getUuid() {
		return uuid.toString();
	}
	
	
	
	

	
	
	
	
}
