/**
 * 
 */
package org.vme.service.dto;

import java.util.UUID;

/**
 * @author Fabrizio Sibeni
 *
 */
public class VmeSearchRefRequestDto {

	/**
	 * UUID of the request. Generated by the system on request action
	 */
	private UUID uuid;
	

	private String concept;
	
	private String lang;
	
	
	
	
	/**
	 * @param uuid
	 */
	public VmeSearchRefRequestDto(UUID uuid) {
		super();
		this.uuid = uuid;
	}
	
	
	
	
	
	
	public String getConcept() {
		return concept;
	}






	public void setConcept(String concept) {
		this.concept = concept;
	}






	public String getLang() {
		return lang;
	}






	public void setLang(String lang) {
		this.lang = lang;
	}






	/**
	 * @return the uuid
	 */
	public String getUuid() {
		return uuid.toString();
	}
	
	
	
	

	
	
	
	
}
