-- This script gives the different sql to be run to split the VME GIS data
-- and produce two table named VME_GIS_BFA and VME_GIS_OARA

-- TABLES
-- ======
-- VME_GIS_BFA
CREATE TABLE FIGIS_GIS.VME_GIS_BFA AS
SELECT
  THE_GEOM,
  VME_ID,
  LOCAL_NAME,
  YEAR,
  END_YEAR,
  OWNER,
  VME_AREA_TIME,
  GLOB_TYPE,
  GLOB_NAME,
  REG_TYPE,
  REG_NAME,
  SURFACE
FROM
  FIGIS_GIS.VMEMEASURES
WHERE
  GLOB_TYPE = 'BTM_FISH';
  
-- VME_GIS_OARA
CREATE TABLE FIGIS_GIS.VME_GIS_OARA AS
SELECT
  THE_GEOM,
  VME_ID,
  LOCAL_NAME,
  YEAR,
  END_YEAR,
  OWNER,
  VME_AREA_TIME,
  GLOB_TYPE,
  GLOB_NAME,
  REG_TYPE,
  REG_NAME,
  SURFACE
FROM
  FIGIS_GIS.VMEMEASURES
WHERE
  GLOB_TYPE = 'OTHER';
  
-- INDEXES
-- =======

-- For both tables, create:
-- > spatial index on 'THE_GEOM' field

CREATE INDEX VME_GIS_BFA_THE_GEOM_IDX
ON FIGIS_GIS.VME_GIS_BFA (THE_GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('TABLESPACE=FI_DATA SDO_RTR_PCTFREE=0')
NOPARALLEL;
COMMIT;

CREATE INDEX VME_GIS_OARA_THE_GEOM_IDX
ON FIGIS_GIS.VME_GIS_OARA (THE_GEOM)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('TABLESPACE=FI_DATA SDO_RTR_PCTFREE=0')
NOPARALLEL;
COMMIT;  
  
-- > attribute indexes
-- (to build from 'VMEMEASURES' DDL in SQL Developer)
  

-- METADATA
--=========

INSERT INTO
  MDSYS.USER_SDO_GEOM_METADATA
VALUES (
  'VME_GIS_BFA',
  'THE_GEOM',
  MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X',-180,180,0.005), MDSYS.SDO_DIM_ELEMENT('Y',-90,90,0.005) ),
  4326
);

INSERT INTO
  MDSYS.USER_SDO_GEOM_METADATA
VALUES (
  'VME_GIS_OARA',
  'THE_GEOM',
  MDSYS.SDO_DIM_ARRAY( MDSYS.SDO_DIM_ELEMENT('X',-180,180,0.005), MDSYS.SDO_DIM_ELEMENT('Y',-90,90,0.005) ),
  4326
);

COMMIT;
